### ISSUE TITLE
mixinbootstrap not set as dependency within twitch

### ISSUE THREAD

**Issue by usafphoenix** [jellysquid3/phosphor-forge#68]
mod install fails due to not recognizing/downloading required dependency. took three hours to figure out why it wasn't working >.>

**Comment by usafphoenix** [comment]
(update: i see it is set when going here: https://www.curseforge.com/minecraft/mc-mods/phosphor-forge/relations/dependencies
but twitch refuses to install the file as it's supposed to, so when creating a new minecraft instance, it still must manually be added....and i always forget

**Comment by jellysquid3** [comment]
I've attempted to coax CurseForge into providing the dependency again, so *hopefully* the Twitch client will automatically download it now. Since said client is unsupported on my platform, I have to rely on user reports. Can you verify that the problem is fixed?

**Comment by usafphoenix** [comment]
Nope. still not installing the dependency. tried it a few times. This really confuses me too cause i can see that it is declared in the curseforge page as having that dependency, and twitch can locate both mods, so....i don't know what's going wrong when it just grabs phosphor and doesn't even try to install mixin.

**Comment by jellysquid3** [comment]
I'm at a loss here. It could be that the launcher doesn't handle dependency resolution correctly because it's an alpha release, but I'm not sure why then it would pick up the *optional* dependency on Phosphor.

**Comment by jellysquid3** [comment]
Does this issue still occur with the Twitch Launcher? The release type has been changed to Beta, which could impact how it behaves.

**Comment by jellysquid3** [comment]
Butterfingers. GitHub should place some kind of confirmation prompt on that button.

**Comment by jellysquid3** [comment]
This looks to be resolved now as of this week.
